/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package module3.hajarhanifah.harga;

/**
 *
 * @author hajarhanifah
 */
public class CekHargaMinuman extends javax.swing.JFrame {

    /**
     * Creates new form CekHargaMinuman
     */
    public CekHargaMinuman() {
        initComponents();
        tfHarga.setEnabled(false);
        getHarga();
    }

    private void getHarga() {
        String merk = (String) lsMerk.getSelectedValue();

        if (merk != null) {
            if (merk.equals("Aqua")) {
                if (rbGelas.isSelected()) {
                    tfHarga.setText("500");
                } else {
                    tfHarga.setText("3000");
                }
            } else {
                if (rbGelas.isSelected()) {
                    tfHarga.setText("450");
                } else {
                    tfHarga.setText("2800");
                }
            }
        } 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lbMerk = new javax.swing.JLabel();
        spMerk = new javax.swing.JScrollPane();
        lsMerk = new javax.swing.JList<>();
        lbSatuan = new javax.swing.JLabel();
        rbGelas = new javax.swing.JRadioButton();
        rbBotol = new javax.swing.JRadioButton();
        lbHarga = new javax.swing.JLabel();
        tfHarga = new javax.swing.JTextField();
        btnBersih = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel1.setText("Pernyataan Nested - If");

        lbMerk.setText("Merk");

        lsMerk.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Aqua", "VIT" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        spMerk.setViewportView(lsMerk);

        lbSatuan.setText("Satuan");

        rbGelas.setText("Gelas");
        rbGelas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbGelasActionPerformed(evt);
            }
        });

        rbBotol.setText("Botol");
        rbBotol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbBotolActionPerformed(evt);
            }
        });

        lbHarga.setText("Harga");

        tfHarga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfHargaActionPerformed(evt);
            }
        });

        btnBersih.setText("Bersih");
        btnBersih.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBersihActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(48, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(127, 127, 127))
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbMerk)
                    .addComponent(lbSatuan)
                    .addComponent(lbHarga))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnBersih, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(rbGelas)
                        .addGap(18, 18, 18)
                        .addComponent(rbBotol))
                    .addComponent(tfHarga)
                    .addComponent(spMerk))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbMerk)
                    .addComponent(spMerk, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbSatuan)
                    .addComponent(rbGelas)
                    .addComponent(rbBotol))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbHarga)
                    .addComponent(tfHarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnBersih)
                .addGap(26, 26, 26))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbGelasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbGelasActionPerformed
        rbBotol.setSelected(false);
        getHarga();
    }//GEN-LAST:event_rbGelasActionPerformed

    private void rbBotolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbBotolActionPerformed
        rbGelas.setSelected(false);
        getHarga();
    }//GEN-LAST:event_rbBotolActionPerformed

    private void tfHargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfHargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfHargaActionPerformed

    private void btnBersihActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBersihActionPerformed
        rbGelas.setSelected(false);
        rbBotol.setSelected(false);
        tfHarga.setText("");
    }//GEN-LAST:event_btnBersihActionPerformed


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CekHargaMinuman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CekHargaMinuman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CekHargaMinuman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CekHargaMinuman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CekHargaMinuman().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBersih;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lbHarga;
    private javax.swing.JLabel lbMerk;
    private javax.swing.JLabel lbSatuan;
    private javax.swing.JList<String> lsMerk;
    private javax.swing.JRadioButton rbBotol;
    private javax.swing.JRadioButton rbGelas;
    private javax.swing.JScrollPane spMerk;
    private javax.swing.JTextField tfHarga;
    // End of variables declaration//GEN-END:variables
}
